water: https://docs.google.com/spreadsheets/d/1F4AWv_seI-DQJ_Gp_N2ziwvGyjnc4KC92GGNXrJRek4/edit?usp=sharing
sediment: https://docs.google.com/spreadsheets/d/1a19q3w2sP7dae8HEzT5TdmfqhRQQd3GItFqiYxWJlxs/edit?usp=sharing
data_quality_control_threshold_date: 2021-11-24
